apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aio-opc-ua-broker-client-certificate
  namespace: azure-iot-operations
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    keyvaultName: <azure-key-vault-name>
    tenantId: <azure-tenant-id>
    objects: |
      array:
        - |
          objectName: assembly-munich-der
          objectType: secret
          objectAlias: assembly-munich.der
          objectEncoding: hex
        - |
          objectName: test-munich-der
          objectType: secret
          objectAlias: test-munich.der
          objectEncoding: hex
        - |
          objectName: packaging-munich-der
          objectType: secret
          objectAlias: packaging-munich.der
          objectEncoding: hex
        - |
          objectName: assembly-seattle-der
          objectType: secret
          objectAlias: assembly-seattle.der
          objectEncoding: hex
        - |
          objectName: test-seattle-der
          objectType: secret
          objectAlias: test-seattle.der
          objectEncoding: hex
        - |
          objectName: packaging-seattle-der
          objectType: secret
          objectAlias: packaging-seattle.der
          objectEncoding: hex
