apiVersion: v1
kind: Namespace
metadata:
  name: softing-edgeconnector-modbus-namespace
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: softing-edgeconnector-modbus
  namespace: softing-edgeconnector-modbus-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: softing-edgeconnector-modbus
  template:
    metadata:
      labels:
        app: softing-edgeconnector-modbus
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: softing-edgeconnector-modbus
        image: softingindustrial/edgeconnector-modbus
        imagePullPolicy: Always
        ports:
        - containerPort: 4897
        - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: softing-edgeconnector-modbus
  namespace: softing-edgeconnector-modbus-namespace
spec:
  type: LoadBalancer
  ports:
  - targetPort: 4897
    port: 4897
    name: softing-edgeconnector-modbus-opcua
  - targetPort: 8099
    port: 8099
    name: softing-edgeconnector-modbus-dashboard
  selector:
    app: softing-edgeconnector-modbus
