apiVersion: v1
kind: Namespace
metadata:
  name: ua-cloudpublisher-namespace
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-cloudpublisher
  namespace: ua-cloudpublisher-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ua-cloudpublisher
  template:
    metadata:
      labels:
        app: ua-cloudpublisher
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: ua-cloudpublisher
        image: ghcr.io/barnstee/ua-cloudpublisher:main
        imagePullPolicy: Always
        env:
        - name: STORAGE_TYPE
          value: "Azure"
        - name: STORAGE_CONNECTION_STRING
          value: "DefaultEndpointsProtocol=https;AccountName=[yourstorageaccountname];AccountKey=[key];EndpointSuffix=core.windows.net"
        - name: STORAGE_CONTAINER_NAME
          value: "ua-cloudpublisher-namespace"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ua-cloudpublisher
  namespace: ua-cloudpublisher-namespace
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: ua-cloudpublisher
