apiVersion: v1
kind: Namespace
metadata:
  name: munich
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-cloudcommander
  namespace: munich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ua-cloudcommander
  template:
    metadata:
      labels:
        app: ua-cloudcommander
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: ua-cloudcommander
        image: ghcr.io/opcfoundation/ua-cloudcommander:main
        imagePullPolicy: Always
        env:
        - name: APPNAME
          value: "commander.munich"
        - name: STORAGE_CONNECTION_STRING
          value: "[mystorageaccountkey1connectionstring]"
        - name: STORAGE_CONTAINER_NAME
          value: "munich"
        - name: USE_KAFKA
          value: "1"
        - name: BROKERNAME
          value: "[myeventhubsnamespace].servicebus.windows.net"
        - name: CLIENTNAME
          value: "commander.munich"
        - name: TOPIC
          value: "commander.command"
        - name: RESPONSE_TOPIC
          value: "commander.response"
        - name: USERNAME
          value: "$ConnectionString"
        - name: PASSWORD
          value: "[myeventhubsnamespaceprimarykeyconnectionstring]"
